Repository upb-uc4/hlf-chaincode, pull requests merged in 2020-09, with the labels that each got.

#17 Feature/private data
  chaincode/collections_config.json
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincode.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincodeTest.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockKeyValue.java
  chaincode/test_configs/AddMatriculationDataTestIO.json
Labels: Hyperledger, enhancement

#18 Update changelog
  CHANGELOG.md
Labels: Hyperledger, documentation

#20 Feature/multi field of study
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/GsonWrapper.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincode.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincodeTest.java
  chaincode/src/test/resources/test_configs/AddEntryToMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/AddMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/GetMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/UpdateMatriculationDataTestIO.json
  chaincode/test_configs/AddEntryToMatriculationDataTestIO.json
Labels: Hyperledger, enhancement

#22 Update changelog v0.7.2
  CHANGELOG.md
Labels: Hyperledger, documentation

#23 solving issue of not recognizing nonexistent MatId in Collection
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincode.java
Labels: Hyperledger

#25 Fix tests not throwing error when querying for empty string
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincodeTest.java
  chaincode/src/test/resources/test_configs/AddEntryToMatriculationDataTestIO.json
Labels: Hyperledger, bug

#26 Update changelog for v0.8.0
  CHANGELOG.md
Labels: Hyperledger, documentation

#27 Release/version 0 8 0
  CHANGELOG.md
  chaincode/collections_config.json
  chaincode/collections_config_dev.json
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/GsonWrapper.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincode.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincodeTest.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockKeyValue.java
  chaincode/src/test/resources/test_configs/AddEntryToMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/AddMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/GetMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/UpdateMatriculationDataTestIO.json
  chaincode/test_configs/AddEntryToMatriculationDataTestIO.json
Labels: Hyperledger, enhancement

#32 EnrollmentId
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincode.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/MatriculationData.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincodeTest.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  chaincode/src/test/resources/test_configs/AddEntryToMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/AddMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/GetMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/UpdateMatriculationDataTestIO.json
Labels: Hyperledger, enhancement

#40 Feature/certificate
  CHANGELOG.md
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/CertificateChaincode.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/CourseChaincode.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincode.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/CertificateContractUtil.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/ContractUtil.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/GsonWrapper.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/MatriculationDataContractUtil.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/CertificateChaincodeTest.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/CourseChaincodeTest.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataChaincodeTest.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockKeyValue.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
  chaincode/src/test/resources/test_configs/certificate_contract/AddCertificateTestIO.json
  chaincode/src/test/resources/test_configs/certificate_contract/GetCertificateTestIO.json
  chaincode/src/test/resources/test_configs/certificate_contract/UpdateCertificateTestIO.json
  chaincode/src/test/resources/test_configs/matriculation_data_contract/AddEntryToMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/matriculation_data_contract/AddMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/matriculation_data_contract/GetMatriculationDataTestIO.json
  chaincode/src/test/resources/test_configs/matriculation_data_contract/UpdateMatriculationDataTestIO.json
Labels: Hyperledger, enhancement
