Repository upb-uc4/hlf-chaincode, pull requests merged in 2020-11, with the labels that each got.

#61 Feature/draft contract
  chaincode/build.gradle
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/ApprovalContract.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/CertificateContract.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataContract.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/error/LedgerStateNotFoundError.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/error/UnprocessableLedgerStateError.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/ApprovalContractUtil.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/CertificateContractUtil.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/ContractUtil.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/MatriculationDataContractUtil.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/ApprovalContractTest.java
  chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
  chaincode/src/test/resources/test_configs/approval_contract/ApproveTransactionTestIO.json
  chaincode/src/test/resources/test_configs/approval_contract/GetApprovalsTestIO.json
Labels: Hyperledger, enhancement

#63 Update matriculation-contract transaction parameters to be consistent
  CHANGELOG.md
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/ContractBase.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContract.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataContract.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/ExaminationRegulation.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/ExaminationRegulationModule.java
  chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/ExaminationRegulationContractUtil.java
Labels: Hyperledger, refactor

#69 Feature/read version from gradle
  .github/workflows/release.yml
  .github/workflows/run_installDist.yml
  .github/workflows/run_tests.yml
  UC4-chaincode/build.gradle
  UC4-chaincode/gradle.properties
  UC4-chaincode/gradle/versioning.gradle
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/ContractBase.java
  UC4-chaincode/src/main/resources/project.properties
Labels: Hyperledger, bug, enhancement

#74 Feature/remove approval checks
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/ContractUtil.java
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/AddMatriculationDataTestIO.json
Labels: Hyperledger

#78 remove constructor, instead "hide"(override) protected variable
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/ContractBase.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataContract.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
Labels: Hyperledger, bug

#72 add "getAll" feature to getExaminationRegulations
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContract.java
Labels: Hyperledger, bug
