Repository upb-uc4/hlf-chaincode, pull requests merged in 2021-01, with the labels that each got.

#90 Feature/fix approval handling
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/ApprovalContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/ContractBase.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/LedgerAccessError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/MissingAccessRightsError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/ParameterError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/Admission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/Approval.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/ApprovalList.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/ExaminationRegulation.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/ExaminationRegulationModule.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/Group.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/MatriculationData.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/SubjectMatriculation.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/SubmissionResult.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/errors/DetailedError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/errors/GenericError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/errors/InvalidParameter.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/AdmissionContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/ApprovalContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/ExaminationRegulationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/GroupContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/MatriculationDataContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/helper/GsonWrapper.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ApprovalContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/CertificateContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/GroupContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/TestCreationBase.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockCompositeKey.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockKeyValue.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/model/JsonIOTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/DropAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/GetAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/approval_contract/ApproveTransactionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/approval_contract/GetApprovalsTestIO.json
  UC4-chaincode/src/test/resources/test_configs/group_contract/AddUserToGroupTestIO.json
  UC4-chaincode/src/test/resources/test_configs/group_contract/GetAllGroupsTestIO.json
  UC4-chaincode/src/test/resources/test_configs/group_contract/GetGroupsForUserTestIO.json
  UC4-chaincode/src/test/resources/test_configs/group_contract/GetUsersForGroupTestIO.json
  UC4-chaincode/src/test/resources/test_configs/group_contract/RemoveUserFromAllGroupsTestIO.json
  UC4-chaincode/src/test/resources/test_configs/group_contract/RemoveUserFromGroupTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/AddMatriculationDataTestIO.json
Labels: Hyperledger, enhancement

#94 Feature/refactor parameter checking
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractBase.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/approval/ApprovalContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/approval/ApprovalContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/LedgerAccessError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/MissingAccessRightsError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/SerializableError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/serializable/LedgerAccessError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/serializable/ParameterError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/serializable/ValidationError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/serializable/ledgeraccess/LedgerStateNotFoundError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/serializable/ledgeraccess/UnprocessableLedgerStateError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/serializable/parameter/MissingTransactionError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/GsonWrapper.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/ExaminationRegulation.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/CertificateContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/helper/AccessManager.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ApprovalContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/CertificateContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/GroupContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/TestCreationBase.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockKeyValue.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/model/JsonIOTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/model/JsonIOTestSetup.java
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/approval_contract/ApproveTransactionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/AddMatriculationDataTestIO.json
Labels: Hyperledger, enhancement, refactor

#99 Fix getAllGroups transaction name in ValidationManager
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
Labels: Hyperledger

#100 Hotfix/version 0 15 1
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
Labels: Hyperledger

#101 Update version regex to accept hotfix numbers
  UC4-chaincode/gradle/versioning.gradle
  UC4-chaincode/src/main/resources/project.properties
Labels: Hyperledger, bug

#102 Hotfix/version 0 15 0 2
  UC4-chaincode/gradle/versioning.gradle
  UC4-chaincode/src/main/resources/project.properties
Labels: Hyperledger, bug

#104 Update changelog
  CHANGELOG.md
Labels: Hyperledger, enhancement

#108 Rename admin group
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/DropAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/AddMatriculationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/GetOperationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/GetOperationsTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/RejectTransactionTestIO.json
Labels: Hyperledger, refactor

#107 feature/operation_state
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/CertificateContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/GroupContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/AddEntriesToMatriculationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/FinishOperationTestIO.json
Labels: Hyperledger, enhancement

#110 Feature/fix tx id bug
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/HyperledgerManager.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
Labels: Hyperledger, bug

#122 Set hash delimiter to ":"
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/GetOperationsTestIO.json
Labels: Hyperledger, bug

#126 Add executing client to existing approvals before validating approval…
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/TestCreationBase.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
Labels: Hyperledger, enhancement

#127 Update CHANGELOG.md
  CHANGELOG.md
Labels: Hyperledger

#128 Add groups of user executing a transaction to approvals before valida…
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
Labels: Hyperledger, enhancement

#124 Read initiator from client id if empty.
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
Labels: Hyperledger, bug

#125 Remove additional info from rejection message
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/resources/test_configs/operation_contract/RejectTransactionTestIO.json
Labels: Hyperledger, enhancement

#136 Feature/pending check
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/OperationData.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/AddMatriculationDataTestIO.json
Labels: Hyperledger, bug

#139 Feature/operation api rework
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/GroupContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  UC4-chaincode/src/test/resources/test_configs/operation_contract/GetOperationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/GetOperationsTestIO.json
Labels: Hyperledger, refactor

#143 Add check for rejection allowed
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/resources/test_configs/operation_contract/RejectTransactionTestIO.json
Labels: Hyperledger, bug

#131 Add enrollmentId and user's groups to existingApprovals only if neces…
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/serializable/ParticipationError.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/FinishOperationTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/RejectTransactionTestIO.json
Labels: Hyperledger, refactor

#146 Feature/require system approve
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/CertificateContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/GroupContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/DropAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/GetAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/certificate_contract/AddCertificateTestIO.json
  UC4-chaincode/src/test/resources/test_configs/certificate_contract/GetCertificateTestIO.json
  UC4-chaincode/src/test/resources/test_configs/certificate_contract/UpdateCertificateTestIO.json
  UC4-chaincode/src/test/resources/test_configs/examination_regulation_contract/AddExaminationRegulationTestIO.json
  UC4-chaincode/src/test/resources/test_configs/examination_regulation_contract/CloseExaminationRegulationTestIO.json
  UC4-chaincode/src/test/resources/test_configs/examination_regulation_contract/GetExaminationRegulationTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/GetMatriculationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/UpdateMatriculationDataTestIO.json
Labels: Hyperledger, enhancement

#147 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#149 Remove access rights from certificate transactions
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
Labels: Hyperledger

#150 Disable base64url padding to get rid of "=" in encodings
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/GetOperationsTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/RejectTransactionTestIO.json
Labels: Hyperledger

#151 Replace transaction names by variables
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractBase.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/CertificateContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/GroupContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
Labels: Hyperledger, refactor

#148 Feature/test attributes
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractBase.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
Labels: Hyperledger, enhancement

#154 Release v0.17.0
  CHANGELOG.md
  UC4-chaincode/build.gradle
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractBase.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/exceptions/serializable/ParticipationError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/OperationData.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/CertificateContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/GroupContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/TestCreationBase.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/DropAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/GetAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/certificate_contract/AddCertificateTestIO.json
  UC4-chaincode/src/test/resources/test_configs/certificate_contract/GetCertificateTestIO.json
  UC4-chaincode/src/test/resources/test_configs/certificate_contract/UpdateCertificateTestIO.json
  UC4-chaincode/src/test/resources/test_configs/examination_regulation_contract/AddExaminationRegulationTestIO.json
  UC4-chaincode/src/test/resources/test_configs/examination_regulation_contract/CloseExaminationRegulationTestIO.json
  UC4-chaincode/src/test/resources/test_configs/examination_regulation_contract/GetExaminationRegulationTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/AddEntriesToMatriculationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/AddMatriculationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/GetMatriculationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/UpdateMatriculationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/FinishOperationTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/GetOperationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/GetOperationsTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/RejectTransactionTestIO.json
  target/global-logging/sbt-global-log11641371700411230572.log
Labels: Hyperledger
