Repository upb-uc4/hlf-chaincode, pull requests merged in 2021-02, with the labels that each got.

#162 check if rejectmessage is empty
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/test/resources/test_configs/operation_contract/RejectTransactionTestIO.json
Labels: Hyperledger, bug

#179 Bugfix/exam prerelease timestamp admission
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/AbstractAdmission.java
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
Labels: Hyperledger, bug

#180 Return error if there is no matriculation for an admission's enrollme…
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/AbstractAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/CourseAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/ExamAdmission.java
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
Labels: Hyperledger, bug

#173 Feature/pending check new
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
Labels: Hyperledger, enhancement

#185 Feature/instant
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/DateSerializer.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/GsonWrapper.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/InstantAdapter.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/Exam.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/OperationData.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/AbstractAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/CourseAdmission.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/GetAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_contract/AddExamTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_contract/GetExamTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
Labels: Hyperledger, bug, refactor

#187 Bugfix/add exam validate exam type
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/exam/Exam.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/exam/ExamType.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExamContractTest.java
  UC4-chaincode/src/test/resources/test_configs/exam_contract/AddExamTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_contract/GetExamTestIO.json
Labels: Hyperledger, enhancement

#197 Refactor typeTokens
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examresult/ExamResultContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examresult/ExamResultContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/GsonWrapper.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/MatriculationData.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/AbstractAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/CourseAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/ExamAdmission.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/CertificateContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExamContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExamResultContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/TestCreationBase.java
Labels: Hyperledger, refactor

#184 Feature/exam prerelease
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examresult/ExamResultContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examresult/ExamResultContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/GsonWrapper.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/InstantAdapter.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/MatriculationData.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/OperationData.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/AbstractAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/AdmissionType.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/CourseAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/ExamAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/UntypedAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/exam/Exam.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/exam/ExamType.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/examresult/ExamResult.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/examresult/ExamResultEntry.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/examresult/GradeType.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/CertificateContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExamContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExamResultContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/TestCreationBase.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/model/JsonIOTestSetup.java
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/DropAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/admission_contract/GetAdmissionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_contract/AddExamTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_contract/GetExamTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_result_contract/AddExamResultTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_result_contract/GetExamResultEntriesTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
Labels: Hyperledger, enhancement

#201 Feature/refactor enum handling
  UC4-chaincode/gradle/test.gradle
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examresult/ExamResultContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/GeneralHelper.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/HyperledgerManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/Dummy.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/ExaminationRegulation/ExaminationRegulation.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/ExaminationRegulation/ExaminationRegulationModule.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/Group.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/AbstractAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/AdmissionType.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/CourseAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/ExamAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/UntypedAdmission.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/errors/DetailedError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/errors/GenericError.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/errors/InvalidParameter.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/exam/Exam.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/exam/ExamType.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/examresult/ExamResult.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/examresult/ExamResultEntry.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/matriculation/MatriculationData.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/matriculation/SubjectMatriculation.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/operation/ApprovalList.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/operation/OperationData.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/operation/OperationDataState.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/operation/TransactionInfo.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExamContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExamResultContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/ExaminationRegulationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/GroupContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/TestCreationBase.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockKeyValue.java
  UC4-chaincode/src/test/resources/test_configs/admission_contract/AddAdmissionTestIO.json
Labels: Hyperledger, refactor

#203 added new test; fixed time format
  UC4-chaincode/src/test/resources/test_configs/exam_result_contract/AddExamResultTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_result_contract/GetExamResultEntriesTestIO.json
Labels: Hyperledger
