Repository upb-uc4/hlf-chaincode, pull requests merged in 2021-03, with the labels that each got.

#200 Feature/pending check
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractBase.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examresult/ExamResultContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/AccessManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/GeneralHelper.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/InstantAdapter.java
  UC4-chaincode/src/main/resources/project.properties
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/util/TestUtil.java
  UC4-chaincode/src/test/resources/test_configs/exam_contract/AddExamTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_contract/GetExamTestIO.json
  UC4-chaincode/src/test/resources/test_configs/exam_result_contract/AddExamResultTestIO.json
  UC4-chaincode/src/test/resources/test_configs/matriculation_data_contract/AddMatriculationDataTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
  UC4-chaincode/src/test/resources/test_configs/operation_contract/RejectTransactionTestIO.json
Labels: Hyperledger, enhancement, refactor

#205 Update changelog
  CHANGELOG.md
Labels: Hyperledger, enhancement

#208 timestamp_error
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/admission/AdmissionContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/certificate/CertificateContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/exam/ExamContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examinationregulation/ExaminationRegulationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/examresult/ExamResultContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/group/GroupContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/matriculationdata/MatriculationDataContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContract.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/operation/OperationContractUtil.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/helper/ValidationManager.java
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/admission/AbstractAdmission.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/AdmissionContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/MatriculationDataContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/OperationContractTest.java
  UC4-chaincode/src/test/java/de/upb/cs/uc4/chaincode/mock/MockChaincodeStub.java
  UC4-chaincode/src/test/resources/test_configs/operation_contract/ApproveTransactionTestIO.json
Labels: Hyperledger, enhancement

#211 Update version
  CHANGELOG.md
  UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/contract/ContractBase.java
Labels: Hyperledger
